"""
批量生成所有实验Notebook - 智能知识库Agent项目
每个实验构建项目的一个模块, 最终在6.3组装
"""
import json, os

COURSE_ROOT = r"G:\CLAUDE CODE_PROJECT\SHIXI\course"

def make_notebook(cells):
    """创建标准 Jupyter notebook JSON"""
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.10.0"}
        },
        "nbformat": 4, "nbformat_minor": 5
    }

def md(source):
    return {"cell_type": "markdown", "metadata": {}, "source": source if isinstance(source, list) else [source]}

def code(source):
    return {"cell_type": "code", "metadata": {}, "outputs": [],
            "source": source if isinstance(source, list) else [source]}

def save_notebook(dirname, filename, cells):
    path = os.path.join(COURSE_ROOT, dirname, filename)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(make_notebook(cells), f, ensure_ascii=False, indent=1)
    print(f"OK: {dirname}/{filename}")

SETUP_CELL = code([
    'import sys, os\n',
    'sys.path.insert(0, "..")\n',
    'from config import get_client, verify_config\n',
    'from agent_project import *\n',
    'from agent_project.tools import create_default_registry\n',
    '\n',
    'client = get_client()\n',
    'print(f"项目模块已加载 | LLM: {client.name} ({client.model})")\n',
])

# ===== 1.4 Prompt Engineering =====
save_notebook("1.4_Prompt_Engineering", "实验_Prompt工程实战.ipynb", [
    md("# 1.4 Prompt Engineering - 提示词优化工厂\n\n为智能知识库Agent构建高质量的Prompt模板库和自动评估系统"),
    md("## 项目定位\n\n本实验产出 `prompts/` 目录下的Prompt模板, 这些模板将被6.3最终项目直接使用"),
    SETUP_CELL,
    code([
        '# Prompt模板库 - 智能知识库Agent的各类Prompt\n',
        'PROMPT_TEMPLATES = {\n',
        '    "system": """你是智能知识库助手。\n',
        '规则:\n',
        '1. 基于提供的文档内容回答问题, 引用来源\n',
        '2. 如果文档中没有相关信息, 明确告知用户\n',
        '3. 回答简洁准确, 不超过500字\n',
        '4. 对于不确定的内容, 标注"[存疑]"\n',
        '5. 使用中文回答""",\n',
        '\n',
        '    "rag_qa": """基于以下知识库内容回答问题:\n',
        '{context}\n',
        '问题: {question}\n',
        '请引用来源编号。如果知识库中没有相关信息, 请明确说明。""",\n',
        '\n',
        '    "agent_react": """你是智能Agent。在Thought-Action-Observation循环中推理。\n',
        '可用工具: {tools}\n',
        '格式:\n',
        'Thought: 思考过程\n',
        'Action: 工具名\n',
        'Action Input: JSON参数\n',
        'Observation: 工具返回\n',
        '...\n',
        'Final Answer: 最终回答""",\n',
        '\n',
        '    "summarize": """请用2-3句话总结以下对话的核心内容:\n',
        '{conversation}\n',
        '摘要:""",\n',
        '}\n',
        '\n',
        'print(f"已加载 {len(PROMPT_TEMPLATES)} 个Prompt模板:")\n',
        'for name in PROMPT_TEMPLATES:\n',
        '    print(f"  - {name}")\n',
    ]),
    code([
        '# Prompt自动评估系统\n',
        'import json, time\n',
        '\n',
        'class PromptEvaluator:\n',
        '    """Prompt质量自动评估器 - A/B测试和评分"""\n',
        '\n',
        '    def __init__(self, llm_client):\n',
        '        self.llm = llm_client\n',
        '        self.results = []\n',
        '\n',
        '    def evaluate(self, prompt_name, template, test_cases, **kwargs):\n',
        '        """用测试用例评估Prompt模板"""\n',
        '        for case in test_cases:\n',
        '            filled = template.format(**{**case, **kwargs})\n',
        '            t0 = time.time()\n',
        '            r = self.llm.chat(filled, temperature=0.3, max_tokens=300)\n',
        '            elapsed = (time.time() - t0) * 1000\n',
        '            score = self._score(r["content"], case.get("expected", ""))\n',
        '            self.results.append({"prompt": prompt_name, "case": case.get("name",""),\n',
        '                "latency_ms": elapsed, "score": score, "tokens": r["usage"]["output"]})\n',
        '            print(f"  [{prompt_name}] {case.get(\'name\',\'?\')}: 评分={score}/100, {elapsed:.0f}ms, {r[\'usage\'][\'output\']}t")\n',
        '\n',
        '    def _score(self, response, expected):\n',
        '        """简单评分: 长度合理 + 关键词匹配"""\n',
        '        s = 0\n',
        '        if 50 < len(response) < 800: s += 40\n',
        '        elif len(response) > 0: s += 20\n',
        '        if expected:\n',
        '            hits = sum(1 for w in expected.split() if w in response)\n',
        '            s += min(40, hits * 10)\n',
        '        if any(w in response for w in ["根据", "来源", "知识库", "文档"]): s += 20\n',
        '        return min(100, s)\n',
        '\n',
        '    def report(self):\n',
        '        """生成评估报告"""\n',
        '        if not self.results: return "无评估数据"\n',
        '        avg_score = sum(r["score"] for r in self.results) / len(self.results)\n',
        '        avg_latency = sum(r["latency_ms"] for r in self.results) / len(self.results)\n',
        '        return f"评估 {len(self.results)} 个案例 | 均分: {avg_score:.0f} | 均延迟: {avg_latency:.0f}ms"\n',
        '\n',
        'evaluator = PromptEvaluator(client)\n',
        'print("PromptEvaluator已就绪")\n',
    ]),
    code([
        '# 实际测试: 对比不同Prompt的效果\n',
        'TEST_CASES = [\n',
        '    {"name": "知识问答", "question": "什么是MCP协议?",\n',
        '     "context": "MCP(Model Context Protocol)是AI Agent标准化协议, 已捐赠Linux Foundation。",\n',
        '     "expected": "MCP Agent 协议 标准"},\n',
        '    {"name": "无相关内容", "question": "今天天气怎么样?",\n',
        '     "context": "(无相关文档)",\n',
        '     "expected": "没有 无法 未找到"},\n',
        ']\n',
        '\n',
        'print("===== Prompt A/B对比测试 =====\\n")\n',
        'for tc in TEST_CASES:\n',
        '    print(f"测试: {tc[\'name\']} | 问题: {tc[\'question\']}")\n',
        '    r = client.chat(\n',
        '        system=PROMPT_TEMPLATES["system"],\n',
        '        messages=[{"role": "user", "content": PROMPT_TEMPLATES["rag_qa"].format(**tc)}],\n',
        '        temperature=0.3, max_tokens=300\n',
        '    )\n',
        '    print(f"  回答: {r[\'content\'][:150]}...")\n',
        '    print()\n',
        '\n',
        'print("===== 结构化输出测试 =====\\n")\n',
        'r = client.chat(\n',
        '    system="你是JSON输出专家。只输出纯JSON。",\n',
        '    messages=[{"role": "user", "content": "分析情感: 这个产品很好用但有点贵。输出JSON: {sentiment, confidence, keywords}"}],\n',
        '    temperature=0.1, max_tokens=150\n',
        ')\n',
        'print(f"JSON输出:\\n{r[\'content\']}")\n',
    ]),
    code([
        '# 导出Prompt模板供项目使用\n',
        'import json\n',
        'os.makedirs("prompts", exist_ok=True)\n',
        'with open("prompts/templates.json", "w", encoding="utf-8") as f:\n',
        '    json.dump(PROMPT_TEMPLATES, f, ensure_ascii=False, indent=2)\n',
        'print("Prompt模板已导出到 prompts/templates.json")\n',
    ]),
])

# ===== 2.1 对话系统 =====
save_notebook("2.1_对话系统开发", "实验_多轮对话系统.ipynb", [
    md("# 2.1 对话系统开发 - ConversationManager\n\n构建智能知识库Agent的对话引擎, 支持多轮对话、上下文管理、记忆压缩"),
    md("## 项目定位\n\n本实验的 ConversationManager 将被6.3最终项目直接使用"),
    SETUP_CELL,
    code([
        '# 创建对话管理器\n',
        'from agent_project.conversation import ConversationManager\n',
        '\n',
        'conv = ConversationManager(\n',
        '    system_prompt="你是智能知识库助手。基于知识库回答问题。",\n',
        '    max_history=20,\n',
        '    max_context_tokens=4000,\n',
        ')\n',
        'print(f"ConversationManager已创建: max_history={conv.max_history}, max_tokens={conv.max_context_tokens}")\n',
    ]),
    code([
        '# 模拟多轮对话\n',
        'print("===== 多轮对话测试 =====\\n")\n',
        '\n',
        '# 第1轮: 用户提问\n',
        'conv.add_user_message("什么是RAG?")\n',
        'r = client.chat(messages=conv.get_context(), temperature=0.3, max_tokens=200)\n',
        'conv.add_assistant_message(r["content"])\n',
        'print(f"[第1轮] 用户: 什么是RAG?")\n',
        'print(f"        助手: {r[\'content\'][:100]}...")\n',
        'print(f"        上下文: {conv.turn_count}轮, ~{conv._token_count}tokens\\n")\n',
        '\n',
        '# 第2轮: 追问 (依赖上下文)\n',
        'conv.add_user_message("那它和普通搜索有什么区别?")\n',
        'r = client.chat(messages=conv.get_context(), temperature=0.3, max_tokens=200)\n',
        'conv.add_assistant_message(r["content"])\n',
        'print(f"[第2轮] 用户: 那它和普通搜索有什么区别?")\n',
        'print(f"        助手: {r[\'content\'][:100]}...")\n',
        'print(f"        上下文: {conv.turn_count}轮\\n")\n',
        '\n',
        '# 第3轮: 继续追问\n',
        'conv.add_user_message("给出一个实际应用的例子")\n',
        'r = client.chat(messages=conv.get_context(), temperature=0.3, max_tokens=200)\n',
        'conv.add_assistant_message(r["content"])\n',
        'print(f"[第3轮] 用户: 给出一个实际应用的例子")\n',
        'print(f"        助手: {r[\'content\'][:100]}...")\n',
        'print(f"        上下文: {conv.turn_count}轮\\n")\n',
    ]),
    code([
        '# 对话历史压缩测试\n',
        'print("===== 历史压缩测试 =====\\n")\n',
        'print(f"压缩前: {conv.turn_count}轮, ~{conv._token_count}tokens")\n',
        'conv._compress_history()\n',
        'print(f"压缩后: {len(conv.messages)}条消息, ~{conv._token_count}tokens")\n',
        'if conv.summary:\n',
        '    print(f"摘要: {conv.summary[:200]}...")\n',
    ]),
    code([
        '# 流式输出演示\n',
        'print("===== 流式输出 =====\\n")\n',
        'print("助手(流式): ", end="")\n',
        'for token in client.chat_stream("用50字介绍智能知识库Agent的工作原理"):\n',
        '    print(token, end="", flush=True)\n',
        'print()\n',
    ]),
    code([
        '# 导出对话状态\n',
        'state = conv.to_dict()\n',
        'print(f"会话状态: {state[\'turn_count\']}轮, {state[\'token_count\']}tokens")\n',
        'print(f"模块就绪: ConversationManager 可被6.3最终项目导入使用")\n',
    ]),
])

# ===== 2.2 多模态 =====
save_notebook("2.2_多模态应用", "实验_多模态应用开发.ipynb", [
    md("# 2.2 多模态应用 - DocumentParser\n\n构建支持PDF/图片/文本的多格式文档解析器, 为RAG系统提供文档摄入能力"),
    md("## 项目定位\n\n本实验的 DocumentPipeline 将被3.2和6.3项目使用"),
    SETUP_CELL,
    code([
        '# 文档解析器测试\n',
        'from agent_project.pipeline import DocumentLoader, TextChunker, DocumentPipeline, Document\n',
        '\n',
        '# 创建样例知识库文档\n',
        'SAMPLE_DOCS = [\n',
        '    {"source": "intro.md", "content": """# 智能知识库Agent介绍\n',
        '智能知识库Agent是一个基于RAG和Agent技术的问答系统。它结合了向量检索和关键词检索,\n',
        '通过混合检索策略提高召回率。同时集成了Agent推理能力, 可以调用外部工具获取信息。\n',
        '核心技术栈: LangGraph + FAISS + BM25 + Qwen3.7。"""},\n',
        '    {"source": "rag.md", "content": """# RAG技术详解\n',
        'RAG(Retrieval-Augmented Generation)检索增强生成是2026年最主流的LLM应用架构。\n',
        '工作流程: 用户提问 -> 文档检索 -> 上下文构建 -> LLM生成 -> 引用标注。\n',
        '高级技术: 混合检索(BM25+向量)、RRF融合、Cross-Encoder重排序、Self-RAG。"""},\n',
        '    {"source": "mcp.md", "content": """# MCP协议介绍\n',
        'MCP(Model Context Protocol)是AI Agent的标准化协议。2025年12月捐赠Linux Foundation。\n',
        '定义三种原语: Tool(操作工具)、Resource(只读数据)、Prompt(可复用模板)。\n',
        '截至2026年6月, 已有10000+公开MCP服务器和9700万月SDK下载量。"""},\n',
        ']\n',
        '\n',
        'pipeline = DocumentPipeline(chunk_size=200, chunk_overlap=30)\n',
        'pipeline.ingest_texts(SAMPLE_DOCS)\n',
        '\n',
        'stats = pipeline.get_stats()\n',
        'print(f"文档管道就绪: {stats[\'documents\']}文档, {stats[\'total_chunks\']}块")\n',
        'print(f"均块大小: {stats[\'avg_chunk_size\']:.0f}字符, 总字符: {stats[\'total_chars\']}")\n',
    ]),
    code([
        '# 展示文档分块结果\n',
        'for doc in pipeline.documents:\n',
        '    print(f"\\n文档: {doc.metadata[\'source\']} ({len(doc.content)}字符) -> {len(doc.chunks)}块")\n',
        '    for i, chunk in enumerate(doc.chunks[:2]):\n',
        '        print(f"  块[{i}]: {chunk[:80]}...")\n',
    ]),
    code([
        '# 实际应用: 将分块结果传递给检索引擎\n',
        'from agent_project.hybrid_search import HybridSearcher\n',
        '\n',
        'searcher = HybridSearcher()\n',
        'searcher.index(pipeline.all_chunks)\n',
        '\n',
        'print(f"检索引擎已索引 {len(pipeline.all_chunks)} 个文本块")\n',
        'print("就绪: DocumentPipeline -> HybridSearcher 管道连通!")\n',
    ]),
])

# ===== 2.3 Function Calling =====
save_notebook("2.3_函数调用与工具使用", "实验_函数调用与工具使用.ipynb", [
    md("# 2.3 Function Calling - ToolRegistry\n\n构建Agent的工具插件系统, 支持动态注册、安全执行和MCP兼容接口"),
    md("## 项目定位\n\n本实验的 ToolRegistry 将被4.1 ReActAgent和6.3最终项目使用"),
    SETUP_CELL,
    code([
        '# 创建工具注册表\n',
        'from agent_project.tools import create_default_registry, SafeCalculator\n',
        '\n',
        'tools = create_default_registry()\n',
        'print(f"已注册工具: {tools.list_tools()}")\n',
        'print(f"工具描述:\\n{tools.get_description()}")\n',
    ]),
    code([
        '# 工具执行测试\n',
        'print("===== 工具执行测试 =====\\n")\n',
        '\n',
        'tests = [\n',
        '    ("search", {"query": "MCP"}),\n',
        '    ("calculator", {"expression": "sqrt(144) + 3 * 5"}),\n',
        '    ("datetime", {}),\n',
        ']\n',
        '\n',
        'for name, args in tests:\n',
        '    result = tools.execute(name, args)\n',
        '    print(f"  {name}({args}): {result[:80]}")\n',
    ]),
    code([
        '# 注册自定义工具: 知识库统计\n',
        'def kb_stats():\n',
        '    """获取知识库统计信息"""\n',
        '    return "知识库: 50篇文档, 320个文本块, 最后更新2026-06-28"\n',
        '\n',
        'tools.register("kb_stats", kb_stats, "获取知识库统计信息",\n',
        '    {"type": "object", "properties": {}, "required": []})\n',
        'print(f"注册新工具后: {tools.list_tools()}")\n',
        'print(tools.execute("kb_stats", {}))\n',
    ]),
    code([
        '# Function Calling: 让LLM自动选择工具\n',
        'print("===== LLM驱动的工具选择 =====\\n")\n',
        '\n',
        'queries = [\n',
        '    "搜索一下MCP协议的定义",\n',
        '    "计算 25 * 4 + 100 / 5",\n',
        '    "现在几点?",\n',
        '    "你好, 今天星期几?",  # 不需要工具\n',
        ']\n',
        '\n',
        'for query in queries:\n',
        '    r = client.chat(\n',
        '        system="你是智能助手。需要时使用工具获取信息。",\n',
        '        messages=[{"role": "user", "content": query}],\n',
        '        tools=tools.get_openai_schemas(),\n',
        '        temperature=0.1, max_tokens=200\n',
        '    )\n',
        '    if r.get("tool_calls"):\n',
        '        tc = r["tool_calls"][0]\n',
        '        result = tools.execute(tc["name"], tc["arguments"])\n',
        '        print(f"  [{tc[\'name\']}] {query} -> {result[:60]}")\n',
        '    else:\n',
        '        print(f"  [直接回答] {query} -> {r[\'content\'][:60]}")\n',
    ]),
])

print("\n所有实验笔记本生成完成!")
